name: Deploy
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi
      url: https://pypi.org/p/wagtail-case-insensitive
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - run: python3 -m pip install --upgrade build && python3 -m build

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
